### PR TITLE
Homework 3-12-15

### PR DESCRIPTION
**Pull request by lcain**
Made the butterflies into dinosaurs, its the exact same.

### CODE REVIEW

**Comment by lcain** [comment]
Movie homework from the weekend. Single search working. Made a second file for multisearch, got it pulling all the movies from omdb and could get it to read what was already on my database but couldnt figure out how to pull an individual movie from the link on the list.

**Comment by lcain** [comment]
Three ruby games complete. Pretty straightforward, finding this stuff easier to wrap my head around than JS. (But I really like JS! I just don't know it very well.) Or maybe I'm finding it easier because of starting out with JS. Either way, its making sense so far!

**Comment by lcain** [comment]
Planets code along turned into Oceans database. Basic, but working. No issues following the same format for planets.

**Comment by lcain** [comment]
The books and authors exercise was a little bit more confusing just because of the short cuts, I liked it better when I could follow each step the long way and see what was going on. With the shortcuts I found that I was trying to figure out exactly what I just did and what was completed for me.

**Comment by lcain** [comment]
Movies III - Finished the basic search for a movie poster. Didn't do anything further with this one. Sorry!

**Comment by lcain** [comment]
Horribly struggling with API's. More than API's just struggling with the language, trying to read documentation and I feel like I'm looking at foreign language. I'm just not understanding the basics again.

**Comment by lcain** [comment]
Not something I could have figured out on my own, had a lot of help going through the flow structure with Kane. But I do understand it. I don't feel like I could replicated it on my own, I'd need to look through an example to follow.

**Comment by ga-wolf** [comment]
It's all looking really good Loretta!

**Pull request merged**
